name: Test Action
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: check commands
        run: pwd
      
      - name: Check ls
        run: ls
      
      - name: Install surge
        run: npm install -g surge
      
      - name: Deploy website on surge
        run: surge ./ https://bustling-stream.surge.sh --token ${{ secrets.TEST_TOKEN}}
